const DB_NAME = "krinyx-local-media";
const STORE = "tracks";
const OPFS_DIR = "krinyx-media";
type LocalMeta = { sourceId: string; title: string; type: string; permanent: boolean; updatedAt: number };

type StorageManagerWithOPFS = StorageManager & { getDirectory?: () => Promise<FileSystemDirectoryHandle> };
async function opfsFile(sourceId: string, create = false) { const storage = navigator.storage as StorageManagerWithOPFS; if (!storage.getDirectory) return undefined; const root = await storage.getDirectory(); const dir = await root.getDirectoryHandle(OPFS_DIR, { create }); return { handle: await dir.getFileHandle(`${encodeURIComponent(sourceId)}.media`, { create }), dir }; }
function openDb(): Promise<IDBDatabase> { return new Promise((resolve, reject) => { const request = indexedDB.open(DB_NAME, 2); request.onupgradeneeded = () => { const db = request.result; if (!db.objectStoreNames.contains(STORE)) db.createObjectStore(STORE, { keyPath: "sourceId" }); }; request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function putMeta(meta: LocalMeta) { const db = await openDb(); await new Promise<void>((resolve, reject) => { const tx = db.transaction(STORE, "readwrite"); tx.objectStore(STORE).put(meta); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); }); db.close(); }
async function getMeta(sourceId: string) { const db = await openDb(); const result = await new Promise<LocalMeta | undefined>((resolve, reject) => { const request = db.transaction(STORE).objectStore(STORE).get(sourceId); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); db.close(); return result; }
export async function saveLocalTrack(sourceId: string, blob: Blob, title: string, permanent = false) { const file = await opfsFile(sourceId, true); if (file) { const writer = await file.handle.createWritable(); await writer.write(blob); await writer.close(); await putMeta({ sourceId, title, type: blob.type, permanent, updatedAt: Date.now() }); return; } const db = await openDb(); await new Promise<void>((resolve, reject) => { const tx = db.transaction(STORE, "readwrite"); tx.objectStore(STORE).put({ sourceId, title, type: blob.type, blob, permanent, updatedAt: Date.now() }); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); }); db.close(); }
export async function getLocalTrack(sourceId: string) { const meta = await getMeta(sourceId); if (!meta) return undefined; const handle = await opfsFile(sourceId); if (handle) { try { const file = await handle.handle.getFile(); return { ...meta, blob: file }; } catch { return undefined; } } const db = await openDb(); const result = await new Promise<any>((resolve, reject) => { const request = db.transaction(STORE).objectStore(STORE).get(sourceId); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); db.close(); return result; }
export async function hasLocalTrack(sourceId: string) { return Boolean(await getLocalTrack(sourceId)); }
export async function listLocalTracks() { const db = await openDb(); const items = await new Promise<LocalMeta[]>((resolve, reject) => { const request = db.transaction(STORE).objectStore(STORE).getAll(); request.onsuccess = () => resolve(request.result as LocalMeta[]); request.onerror = () => reject(request.error); }); db.close(); return Promise.all(items.map(async item => ({ ...item, blob: (await getLocalTrack(item.sourceId))?.blob }))); }
export async function removeTemporaryTracks(keepSourceIds: string[]) { const db = await openDb(); await new Promise<void>((resolve, reject) => { const tx = db.transaction(STORE, "readwrite"); const request = tx.objectStore(STORE).openCursor(); request.onsuccess = async () => { const cursor = request.result; if (!cursor) return; const item = cursor.value as LocalMeta; if (!item.permanent && !keepSourceIds.includes(item.sourceId)) { try { const file = await opfsFile(item.sourceId); await file?.dir.removeEntry(`${encodeURIComponent(item.sourceId)}.media`); } catch {} cursor.delete(); } cursor.continue(); }; tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); }); db.close(); }
export async function cacheStreamResponse(url: string, sourceId: string, title: string, permanent = false) { const response = await fetch(url, { credentials: "include" }); if (!response.ok) throw new Error("Le flux n’est pas disponible."); const blob = await response.blob(); await saveLocalTrack(sourceId, blob, title, permanent); return URL.createObjectURL(blob); }
export async function preloadLocalQueue(tracks: { id: string; title: string; url?: string }[]) { for (const track of tracks.slice(0, 5)) { if (!track.url || await hasLocalTrack(track.id)) continue; try { await cacheStreamResponse(track.url, track.id, track.title, false); } catch {} } }
export async function registerLocalStorageWorker() { if ("serviceWorker" in navigator) await navigator.serviceWorker.register("/sw.js", { scope: "/" }); }
