import { Router } from "express";
import crypto from "node:crypto";
import { getCurrentUser, pool } from "./auth.ts";

const CLIENT_ID = process.env.SPOTIFY_CLIENT_ID || "";
const CLIENT_SECRET = process.env.SPOTIFY_CLIENT_SECRET || "";
const pendingStates = new Map<string, { userId: string; expiresAt: number }>();
const key = crypto.createHash("sha256").update(process.env.SPOTIFY_TOKEN_ENCRYPTION_KEY || process.env.JWT_SECRET || "krinyx-change-this-key").digest();

function encrypt(value: string) { const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv("aes-256-gcm", key, iv); const encrypted = Buffer.concat([cipher.update(value, "utf8"), cipher.final()]); return `${iv.toString("hex")}:${cipher.getAuthTag().toString("hex")}:${encrypted.toString("hex")}`; }
function decrypt(value: string) { const [ivHex, tagHex, dataHex] = value.split(":"); const decipher = crypto.createDecipheriv("aes-256-gcm", key, Buffer.from(ivHex, "hex")); decipher.setAuthTag(Buffer.from(tagHex, "hex")); return Buffer.concat([decipher.update(Buffer.from(dataHex, "hex")), decipher.final()]).toString("utf8"); }
function redirectUri(req: any) { if (process.env.SPOTIFY_REDIRECT_URI) return process.env.SPOTIFY_REDIRECT_URI; const proto = String(req.headers["x-forwarded-proto"] || (req.secure ? "https" : "http")).split(",")[0].trim(); const host = String(req.headers["x-forwarded-host"] || req.headers.host || "127.0.0.1:3000").split(",")[0].trim(); return `${proto}://${host}/api/spotify/callback`; }
function configured() { return Boolean(CLIENT_ID && CLIENT_SECRET && pool); }
async function spotifyRequest(path: string, token: string, params?: RequestInit) { const response = await fetch(`https://api.spotify.com/v1${path}`, { ...params, headers: { Authorization: `Bearer ${token}`, ...(params?.headers || {}) } }); const data = await response.json(); if (!response.ok) throw new Error(data?.error?.message || "Spotify a refusé la requête."); return data; }

async function tokenForUser(userId: string) {
  if (!pool) return undefined;
  const result = await pool.query(`SELECT access_token, refresh_token, token_expires_at, scope FROM krinyx_spotify_accounts WHERE user_id = $1`, [userId]);
  const account = result.rows[0]; if (!account) return undefined;
  if (new Date(account.token_expires_at).getTime() > Date.now() + 60000) return decrypt(account.access_token);
  if (!account.refresh_token) return undefined;
  const auth = Buffer.from(`${CLIENT_ID}:${CLIENT_SECRET}`).toString("base64");
  const response = await fetch("https://accounts.spotify.com/api/token", { method: "POST", headers: { Authorization: `Basic ${auth}`, "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ grant_type: "refresh_token", refresh_token: decrypt(account.refresh_token) }) });
  const data = await response.json(); if (!response.ok) return undefined;
  await pool.query(`UPDATE krinyx_spotify_accounts SET access_token = $1, refresh_token = COALESCE($2, refresh_token), token_expires_at = NOW() + ($3 * INTERVAL '1 second'), updated_at = NOW() WHERE user_id = $4`, [encrypt(data.access_token), data.refresh_token ? encrypt(data.refresh_token) : null, Number(data.expires_in || 3600), userId]);
  return data.access_token;
}

export const spotifyRouter = Router();
spotifyRouter.get("/status", async (req, res) => { const user = await getCurrentUser(req); const account = user && pool ? await pool.query(`SELECT spotify_user_id, updated_at FROM krinyx_spotify_accounts WHERE user_id = $1`, [user.id]) : null; res.json({ configured: configured(), connected: Boolean(account?.rows[0]), user: user ? { id: user.id, name: user.name } : null }); });
spotifyRouter.get("/login", async (req, res) => { const user = await getCurrentUser(req); if (!user) return res.status(401).send("Connectez-vous à Krinyx avant de lier Spotify."); if (!configured()) return res.status(503).send("Spotify ou la base de données n'est pas configuré."); for (const [key, value] of pendingStates) if (value.expiresAt < Date.now()) pendingStates.delete(key); if (pendingStates.size >= 10000) return res.status(503).send("Service Spotify temporairement indisponible."); const state = crypto.randomBytes(24).toString("hex"); pendingStates.set(state, { userId: user.id, expiresAt: Date.now() + 600000 }); const params = new URLSearchParams({ client_id: CLIENT_ID, response_type: "code", redirect_uri: redirectUri(req), state, scope: "playlist-read-private playlist-read-collaborative" }); res.redirect(`https://accounts.spotify.com/authorize?${params}`); });
spotifyRouter.get("/callback", async (req, res) => { const { code, state, error } = req.query as Record<string, string | undefined>; const pending = state ? pendingStates.get(state) : undefined; const userId = pending && pending.expiresAt > Date.now() ? pending.userId : undefined; if (state) pendingStates.delete(state); if (error) return res.redirect("/?spotify=cancelled"); if (!code || !state || !userId || !pool) return res.status(400).send("Callback Spotify invalide ou expiré."); try { const auth = Buffer.from(`${CLIENT_ID}:${CLIENT_SECRET}`).toString("base64"); const response = await fetch("https://accounts.spotify.com/api/token", { method: "POST", headers: { Authorization: `Basic ${auth}`, "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ grant_type: "authorization_code", code, redirect_uri: redirectUri(req) }) }); const data = await response.json(); if (!response.ok) throw new Error(data?.error_description || "La connexion Spotify a échoué."); const profile = await spotifyRequest("/me", data.access_token); await pool.query(`INSERT INTO krinyx_spotify_accounts (id, user_id, spotify_user_id, access_token, refresh_token, token_expires_at, scope) VALUES ($1, $2, $3, $4, $5, NOW() + ($6 * INTERVAL '1 second'), $7) ON CONFLICT (user_id) DO UPDATE SET spotify_user_id = EXCLUDED.spotify_user_id, access_token = EXCLUDED.access_token, refresh_token = COALESCE(EXCLUDED.refresh_token, krinyx_spotify_accounts.refresh_token), token_expires_at = EXCLUDED.token_expires_at, scope = EXCLUDED.scope, updated_at = NOW()`, [crypto.randomUUID(), userId, profile.id, encrypt(data.access_token), data.refresh_token ? encrypt(data.refresh_token) : null, Number(data.expires_in || 3600), data.scope || ""]); res.redirect("/?spotify=connected"); } catch (err) { console.error("[Spotify callback]", err); res.redirect("/?spotify=error"); } });
spotifyRouter.get("/playlists", async (req, res) => { const user = await getCurrentUser(req); if (!user) return res.status(401).json({ error: "Connectez-vous à Krinyx avant d'importer Spotify." }); const token = await tokenForUser(user.id); if (!token) return res.status(401).json({ error: "Liez d'abord votre compte Spotify." }); try { const data = await spotifyRequest("/me/playlists?limit=50", token); res.json({ playlists: data.items.map((item: any) => ({ id: item.id, name: item.name, image: item.images?.[0]?.url || "", tracks: item.items?.total || item.tracks?.total || 0 })) }); } catch (error) { res.status(502).json({ error: error instanceof Error ? error.message : "Impossible de charger les playlists." }); } });
spotifyRouter.get("/playlists/:id/tracks", async (req, res) => { const user = await getCurrentUser(req); const token = user && await tokenForUser(user.id); if (!token) return res.status(401).json({ error: "Liez d'abord votre compte Spotify." }); try { const data = await spotifyRequest(`/playlists/${encodeURIComponent(req.params.id)}/tracks?limit=100`, token); res.json({ tracks: data.items.map((item: any) => item.track).filter(Boolean).map((track: any) => ({ title: track.name, artist: track.artists?.map((artist: any) => artist.name).join(", ") || "", album: track.album?.name || "" })) }); } catch (error) { res.status(502).json({ error: error instanceof Error ? error.message : "Impossible de charger cette playlist." }); } });
spotifyRouter.post("/unlink", async (req, res) => { const user = await getCurrentUser(req); if (user && pool) await pool.query(`DELETE FROM krinyx_spotify_accounts WHERE user_id = $1`, [user.id]); res.json({ ok: true }); });
